apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: all-components
  description: A collection of all Kolibri components
spec:
  targets:
    - ./components/backend/catalog-info.yaml
    - ./components/frontend/catalog-info.yaml
    - ./components/design/catalog-info.yaml